In [1]:
print("hello I am excited to learn Pytorch")


hello I am excited to learn Pytorch


In [2]:
!nvidia-smi

Sat Sep  2 11:56:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.0.1+cu118


**CREATING TENSORS**

In [4]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector
vector=torch.tensor([7,7])

In [8]:
vector


tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8269, 0.7477, 0.5562, 0.9602],
        [0.2345, 0.4679, 0.9195, 0.1747],
        [0.6687, 0.4803, 0.8450, 0.2685]])

In [14]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

**RANGE OF TENSORS**

In [17]:
torch.range(0,10)

<ipython-input-17-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
torch.__version__

'2.0.1+cu118'

In [19]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
one_to_ten=torch.arange(1,11)

In [21]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
jump=torch.arange(start=0,end=1000,step=77)

In [23]:
jump

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

**TENSOR DATATYPES
**

In [31]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #what datatype is the tensor
                             device=None, #what device is on your tensor
                             requires_grad=False) #whether or not to track gradients with these tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor=float_32_tensor.type(torch.float16)
#OR  float_16_tensor=float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [40]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [42]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [43]:
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
%%time

value=0

for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 2.2 ms, sys: 0 ns, total: 2.2 ms
Wall time: 2.22 ms


In [46]:
%%time

torch.matmul(tensor,tensor)

CPU times: user 857 µs, sys: 0 ns, total: 857 µs
Wall time: 864 µs


tensor(14)

In [48]:
torch.max(tensor)

tensor(3)

In [49]:
tensor.max()

tensor(3)

In [52]:
torch.mean(tensor.type(torch.float32))

tensor(2.)

RuntimeError: ignored